apiVersion: certificate.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authenticated
  usages:
    - client auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTZveXA4WnZiZ1BlaWNUQTAyYWVnMXF2RnpGeGJiTURXQy8zWXFjMUZ5T2tRCjJqckpMcURjTWdpUThSQVdORE9HRnQwOGMvckRxdFVEa2pUYXd0SDBCVVBsekVBbWUvZDhCOGo4MkZaOWJqNmkKNC9HWmRNWVNOV0JaU3JxU1k3am52czhka29vcHFER3pUWVlyT3EvalBWMm9EUEZnakdLL2NqQUFJYnNqcmdnVQpzSGdKbzJkMS8rdzQ0eHM5V0UyNXE3Sk1yencvM1Z5bW5TNWRYSkJ5b1luczVTeGVPQ2lCNk8zYWNNQk9Zb0M4Ci9LVWtwQVpiLzhBNGZ5amlGWUJJMGF6d2VrWHJJNEdBZDlJbzJIMEw0Rnd5Ump5S0YzeW9HRWZ6RHNVcGtDQ2QKQUZJOGJOMkRhU3ByTHRIZDZRZ1Vqa2JMWGE1QVNodXZEclZ6UXpUTHJRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQnpVSE9HeGdGTEIzMFloRGVmdEhIdDd3QnBNbGU5UnB3enpxdUlWL04vaEVtbVd2VWkrClVBTXRub1R3eEMzc0dZcmJsZ2UwMlZpMnVVUEc2Z09LS2ovMWM3dWZmaVNTb2FDVWJDZmhBQmhvYVprWUNoaE0KdlBQaDRGOWd4T2JncSs5RDhqM1l3K1k4ZVhVS1FEdHR0M3VzVFE1WHdLTkIrLzExakRnU25GOHdMWTN4Y1o3aQpQVktTejAyMU9YK3JWcWduMjQzalhRTElQbitXbUVZOHBQT2I2SjBOSVMwRWl5RFZzNXZXWmFlN0pBeW5ZRmtmCmw3alFGelEyQnF0N2diSExMa2Q3ZW9vM0pOaGVOUkFLbWE0andCSVl1UCs0cjJHNG9EMFh6c1daYWh1Q2hJUHgKenRNT1RLcTFhOWp6VkFieDFlczhyc3VJNHcyZUNSUWtCa2s9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client